---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ab3yaml
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: false
  sourceRef:
    kind: "GitRepository"
    name: "ab3yaml"

